#=============================================================================
# Travis Tide settings
#=============================================================================

#=============================================================================
# Environment
#=============================================================================
env:
  global:
    - SPACK_ROOT=$TRAVIS_BUILD_DIR/spack
    - PATH=$SPACK_ROOT/bin:$PATH

#=============================================================================
# Build matrix
#   - Do not use osx_image otherwise brew fails
#     (mpich depends on gcc and brew link fails)
#=============================================================================
matrix:
  fast_finish: true
  include:
    - language: cpp
      os: linux
      dist: trusty
      sudo: true
      env: [ MPI=mpich]
    - language: cpp
      os: osx
      sudo: false
      env: [ MPI=openmpi]

#=============================================================================
# Common Packages
#=============================================================================
addons:
  apt:
    packages:
      - environment-modules

#=============================================================================
# Install dependencies / setup Spack
#=============================================================================
install:
  - .travis/install_dependencies.sh $MPI
  - .travis/setup_spack.sh

#=============================================================================
# Build NEURON
#=============================================================================
script:
  - echo "------- SHOW SPACK CONFIGURATIONS -------"
  - spack compilers
  - spack config get packages

  - echo "------- INSTALL ALL VERSIONS -------"
  - .travis/install_tide.sh

  - echo "------- INSTALLED VERSIONS (WITH DEPENDENCY DAG) -------"
  - spack find -d -v tide

  - echo "------- INSTALLED VERSIONS LIST  -------"
  - spack find -v tide

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    on_success: change
